# Generated by Django 4.2.4 on 2023-08-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=127)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("criado_em", models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
