# Generated by Django 4.2.4 on 2023-08-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
