# Generated by Django 4.2.4 on 2023-08-15 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaConsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_consumo", models.IntegerField(blank=True)),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metas_consumo",
                        to="pessoas.pessoa",
                    ),
                ),
            ],
        ),
    ]
