# Generated by Django 4.2.4 on 2023-08-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        help_text="Por favor, inserir valor inteiro em ml"
                    ),
                ),
                ("criado_em", models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
